/* eslint-disable prettier/prettier */
export enum ErrorsType {
  NOT_FOUND = 'NOT_FOUND',
  CANNOT_BE_DELETED = 'CANNOT_BE_DELETED',
  CPF_ALREADY_REGISTERED = 'CPF_ALREDY_REGISTERED',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  EMAIL_OR_PASSWORD_INCORRECT = 'EMAIL_OR_PASSWORD_INCORRECT',
}
